title: "Pirates World DevLog"
description: "Follow the development journey of our pirate adventure game"
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# GitHub Pages ayarları
baseurl: "/devlog" # repo içinde alt klasördeyse devlog yazmalısın
url: "https://cenairaclub.github.io"

# Varsayılan layout ayarları
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
